"""Initial migration.

Revision ID: 5c20350a8add
Revises: 
Create Date: 2022-06-21 14:26:33.191373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c20350a8add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    data_upgrages()
    # ### end Alembic commands ###

def data_upgrages():
    table = sa.sql.table('categories', sa.sql.column('name'))

    op.bulk_insert(table,
        [
            { 'name': 'Програмирование' },
            { 'name': 'Математика' },
            { 'name': 'Языкознание' },
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
