"""Initial migration.

Revision ID: 18391ed5f54f
Revises: 
Create Date: 2022-06-23 14:39:50.002437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18391ed5f54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name=op.f('fk_users_role_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_review', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_review'], ['books.id'], name=op.f('fk_reviews_book_review_books')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_reviews_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.add_column('images', sa.Column('book_img', sa.Integer(), nullable=True))
    op.drop_constraint('fk_images_book_img_books', 'images', type_='foreignkey')
    op.create_foreign_key(op.f('fk_images_book_img_books'), 'images', 'books', ['book_img'], ['id'])
    op.drop_column('images', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_images_book_img_books'), 'images', type_='foreignkey')
    op.create_foreign_key('fk_images_book_img_books', 'images', 'books', ['book_id'], ['id'])
    op.drop_column('images', 'book_img')
    op.drop_table('reviews')
    op.drop_table('users')
    # ### end Alembic commands ###
